# Generated by Django 2.2.6 on 2019-10-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca_produto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
